# See usage of https://github.com/kubernetes/code-generator if regeneration of the following is required:
#       apis/integrations.flux/zz_generated.deepcopy.go
#       integrations/client/*
#
required = ["k8s.io/code-generator/cmd/client-gen"]

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "k8s.io/code-generator"
  revision = "306be794f1b124a9c939ab168e9ea3944387e66b"

# goland/dep does not follow k8s.io/code-generator's Godeps.json and gengo's master
# version does not work with release-1.8 k8s.io/code-generator. So we have to
# override it.
[[override]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.7.2"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "b610ffd3f8786563002bd5b6a9951d56f64a4921"
