---
  apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: fluxhelmresources.integrations.flux
  spec:
    group: integrations.flux
    names:
      kind: FluxHelmResource
      listKind: FluxHelmResourceList
      plural: fluxhelmresources
    scope: Namespaced
    version: v1   
---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: helm-operator
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: helm-operator
      spec:
        # The serviceAccount is only needed for Kubernetes with RBAC.
        # You will also need to create the resources in flux-account.yaml.
        # serviceAccount: flux
        volumes:
        - name: git-key
          secret:
            secretName: flux-git-deploy
        containers:
        - name: helm-operator
          # There are no ":latest" images for helm-operator. Find the most recent
          # release or image version at https://quay.io/weaveworks/flux (both have the same latest tag)
          # and replace the tag here.
          image: quay.io/weaveworks/helm-operator:flux-helm-operator2-53d5187
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: git-key
            mountPath: /etc/fluxd/ssh
          args:
  
          # replace (at least) the following URL
          - --git-url=git@github.com:weaveworks/helm-fhr-test
          - --git-branch=master
          - --git-charts-path=charts
          # include these next two to connect to an "upstream" service
          # (e.g., Weave Cloud). The token is particular to the service.
          # - --connect=wss://cloud.weave.works/api/flux
          # - --token=abc123abc123abc123abc123
